import React from 'react';
import type { FieldValues, UseFormReturn } from 'react-hook-form';
import type {
  CompositeField,
  /* eslint-disable-next-line @typescript-eslint/no-unused-vars */
  ReactFormMakerStep,
} from '../../interfaces/FieldInterfaces';
import { StepperProvider } from './StepperContext';
import { StepperContent } from './SteppersElements/StepperContent';
import FooterStepperReactHookForm from './SteppersElements/FooterSteppers.component';
import { Stepper } from './SteppersElements/Stepper.component';
import NavigationStepper from './SteppersElements/HeaderStepper/HeaderStepper.componenent';
import { useStepperItemsMap } from './SteppersElements/useStepperItemMap.hook';

interface StepperFormProps<T extends FieldValues> {
  form: UseFormReturn<T>;
  formfields: CompositeField[];
  zObject: any; // eslint-disable-line @typescript-eslint/no-explicit-any
  orientation: 'horizontal' | 'vertical';
  formFieldsMap: (dataField: CompositeField[]) => (React.JSX.Element | null)[];
}

/**
 * ### StepperForm Component
 *
 * The StepperForm component is the complete component that manages the forms generated by React Form Maker under a Stepper distribution interface.
 *
 * ---
 *
 * #### Behavior
 *
 * ##### It intuitively to its own size.
 * To avoid overloading className configurations, ReactFormMaker's StepperForm compoenent adapts its ergonomics to the layout. In vertical mode, for example, if the space allocated to it is too small for the display to be adapted to the user experience. The component will naturally choose a more suitable format.
 *
 * ##### Advanced management of the form.
 *
 * The StepperForm is managed by the `ReactFormMakerStep` interface. This interface includes functions handlers that allow you to interact with the various states of the form throughout its lifecycle. So you can influence and control the form at any time.
 *
 * For more information, see the {@link ReactFormMakerStep} interface.
 *
 * ---
 * @param
 * @returns
 */
function StepperForm<T extends FieldValues>({
  form,
  formfields,
  zObject,
  orientation,
  formFieldsMap: FormFieldsMap,
}: StepperFormProps<T>) {
  const { StepperItemsMap } = useStepperItemsMap(FormFieldsMap);
  return (
    <StepperProvider<T>
      form={form}
      formfields={formfields}
      zObject={zObject} // eslint-disable-line @typescript-eslint/no-unsafe-assignment
      orientation={orientation}
    >
      <Stepper<T>>
        <NavigationStepper />
        <div className="flex flex-col min-w-0 flex-auto">
          <StepperContent className="flex flex-row min-h-[400px]">
            {StepperItemsMap(formfields)}
          </StepperContent>
          <FooterStepperReactHookForm />
        </div>
      </Stepper>
    </StepperProvider>
  );
}

export default StepperForm;
