import { StepElement } from '../../StepperContext.interface';
import { SizeElement } from '../HeaderStepper.hook';
/* eslint-disable-next-line @typescript-eslint/no-unused-vars */
import type { ReactFormMakerStep } from '@/components/ReactFormMaker/interfaces/FieldInterfaces';

/**
 * **Properties for the HeaderStepperItem component**
 * @interface HeaderStepperItemProps
 *
 * ---
 *
 * @param {StepElement} step - The step element. See {@link StepElement}
 * @param {SizeElement} size - The size of the step element. See {@link SizeElement}
 * @param {number} index - The index of the step element.
 */
export type HeaderStepperItemProps = {
  step: StepElement;
  size: SizeElement;
  index: number;
};

/**
 * ### HeaderStepperItem Component
 *
 * This component represents an item in the header stepper.
 * It uses the `useHeaderStepperItem` hook to manage its state and behavior.
 *
 * The items represent the control points of the breadcrumb trail generated by navigation from the configuration passed in the form and the various ReactFormMakerSteps that make it up.
 *
 * See {@link ReactFormMakerStep}
 *
 * ---
 *
 * @param {HeaderStepperItemProps} props - The properties for the component.
 * @param {StepElement} props.step - The step element.
 * @param {SizeElement} props.size - The size of the step element.
 * @param {number} props.index - The index of the step element.
 */
export type HeaderStepperItemInterface = React.ForwardRefExoticComponent<
  HeaderStepperItemProps & React.RefAttributes<HTMLDivElement>
> & {
  displayName?: string;
};
